checks:
  php: true

filter:
  paths:
    - "/*"
  excluded_paths:
    - "/config/*"
    - "/runtime/*"
    - "/tests/Support/*"
    - "/vagrant/*"
    - "/vendor/*"

build:
  image: default-bionic

  environment:
    variables:
      YII_ENV: test

    php:
      version: 8.4.7
      ini:
        xdebug.mode: coverage

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    codeception:
      dependencies:
        override:
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      tests:
        override:
          - command: vendor/bin/codecept run --coverage-xml
            on_node: 1
            coverage:
              file: runtime/_output/coverage.xml
              format: php-clover
