name: build

permissions:
  contents: read

on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".editorconfig"
      - ".gitattributes"
      - ".gitignore"
      - "docker-compose.yml"
      - "docs/**"
      - "LICENSE"
      - "README.md"

  push: *ignore-paths

jobs:
  codeception:
    uses: yiisoft/yii2-actions/.github/workflows/codeception.yml@master
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      codeception-command: vendor/bin/codecept run --env php-builtin --coverage-xml
      coverage-file: tests/support/output/coverage.xml
      extensions: dom, json, gd, imagick, pdo_sqlite
      php-version: '["8.3","8.4","8.5"]'
